CLASS zcl_student_post_process DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC
  FOR EVENTS OF ZRAP_R_STUDENT.

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_student_post_process IMPLEMENTATION.
ENDCLASS.
